//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicFlic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PicFlic.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string p1_btn_login {
            get {
                return ResourceManager.GetString("p1_btn_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember My Choice.
        /// </summary>
        public static string p1_chkBox_remember {
            get {
                return ResourceManager.GetString("p1_chkBox_remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to....
        /// </summary>
        public static string p1_txtBlock_connect {
            get {
                return ResourceManager.GetString("p1_txtBlock_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string p1_txtBlock_pwd {
            get {
                return ResourceManager.GetString("p1_txtBlock_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***Flick your Pics in cloud***.
        /// </summary>
        public static string p1_txtBlock_tagline {
            get {
                return ResourceManager.GetString("p1_txtBlock_tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName:.
        /// </summary>
        public static string p1_txtBlock_uname {
            get {
                return ResourceManager.GetString("p1_txtBlock_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either &apos;Username&apos; or &apos;Password&apos; is empty.
        /// </summary>
        public static string p1_user_msg_emptyfields {
            get {
                return ResourceManager.GetString("p1_user_msg_emptyfields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        public static string p1_user_msg_invalidemail {
            get {
                return ResourceManager.GetString("p1_user_msg_invalidemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connected to.
        /// </summary>
        public static string p1_user_msg_login_sucess {
            get {
                return ResourceManager.GetString("p1_user_msg_login_sucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the target drive....
        /// </summary>
        public static string p1_user_msg_selectdrive {
            get {
                return ResourceManager.GetString("p1_user_msg_selectdrive", resourceCulture);
            }
        }
    }
}
