//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicFlic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PicFlic.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOURCE &amp; LICENSE:The maintenance of your pictures over the Free Google Cloud Service nicknamed Picasa would be very easy using the application. This app uses the free picasa api and abides to their normal usases terms &amp; conditions.
        /// </summary>
        public static string p1_aboutApp {
            get {
                return ResourceManager.GetString("p1_aboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Features:.
        /// </summary>
        public static string p1_aboutApp1 {
            get {
                return ResourceManager.GetString("p1_aboutApp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Persistant Login to cloud service.
        /// </summary>
        public static string p1_aboutApp2 {
            get {
                return ResourceManager.GetString("p1_aboutApp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Create New Album, Upload new pics.
        /// </summary>
        public static string p1_aboutApp3 {
            get {
                return ResourceManager.GetString("p1_aboutApp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Take a pic &amp; upload directly.
        /// </summary>
        public static string p1_aboutApp4 {
            get {
                return ResourceManager.GetString("p1_aboutApp4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Zoom &amp; pinch single picture view to enoy HD pics.
        /// </summary>
        public static string p1_aboutApp5 {
            get {
                return ResourceManager.GetString("p1_aboutApp5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -Delete unwanted pics easily while browsing pics.
        /// </summary>
        public static string p1_aboutApp6 {
            get {
                return ResourceManager.GetString("p1_aboutApp6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PicFlic is already Pinned.
        /// </summary>
        public static string p1_alreadyPinned {
            get {
                return ResourceManager.GetString("p1_alreadyPinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed, please cCheck your Email and Password.
        /// </summary>
        public static string p1_authFailed {
            get {
                return ResourceManager.GetString("p1_authFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string p1_btn_login {
            get {
                return ResourceManager.GetString("p1_btn_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember My Choice.
        /// </summary>
        public static string p1_chkBox_remember {
            get {
                return ResourceManager.GetString("p1_chkBox_remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection with Flickr is under construction....
        /// </summary>
        public static string p1_flickr_underconstruction_msg {
            get {
                return ResourceManager.GetString("p1_flickr_underconstruction_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to....
        /// </summary>
        public static string p1_txtBlock_connect {
            get {
                return ResourceManager.GetString("p1_txtBlock_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string p1_txtBlock_pwd {
            get {
                return ResourceManager.GetString("p1_txtBlock_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***Flick your Pics in cloud***.
        /// </summary>
        public static string p1_txtBlock_tagline {
            get {
                return ResourceManager.GetString("p1_txtBlock_tagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string p1_txtBlock_uname {
            get {
                return ResourceManager.GetString("p1_txtBlock_uname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to authrize from google, excetion=.
        /// </summary>
        public static string p1_unableToAuth {
            get {
                return ResourceManager.GetString("p1_unableToAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either &apos;Username&apos; or &apos;Password&apos; is empty.
        /// </summary>
        public static string p1_user_msg_emptyfields {
            get {
                return ResourceManager.GetString("p1_user_msg_emptyfields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        public static string p1_user_msg_invalidemail {
            get {
                return ResourceManager.GetString("p1_user_msg_invalidemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connected to.
        /// </summary>
        public static string p1_user_msg_login_sucess {
            get {
                return ResourceManager.GetString("p1_user_msg_login_sucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose the target drive....
        /// </summary>
        public static string p1_user_msg_selectdrive {
            get {
                return ResourceManager.GetString("p1_user_msg_selectdrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string p2_2_txtBlock_Private {
            get {
                return ResourceManager.GetString("p2_2_txtBlock_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string p2_2_txtBlock_Public {
            get {
                return ResourceManager.GetString("p2_2_txtBlock_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string p2_2_txtBlock_Submit {
            get {
                return ResourceManager.GetString("p2_2_txtBlock_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PicFlic&gt;New Album Form.
        /// </summary>
        public static string p2_2_txtBlock_Title {
            get {
                return ResourceManager.GetString("p2_2_txtBlock_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the album info:.
        /// </summary>
        public static string p2_2_txtBlock1 {
            get {
                return ResourceManager.GetString("p2_2_txtBlock1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album Name: *.
        /// </summary>
        public static string p2_2_txtBlock2 {
            get {
                return ResourceManager.GetString("p2_2_txtBlock2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (Optional):.
        /// </summary>
        public static string p2_2_txtBlock3 {
            get {
                return ResourceManager.GetString("p2_2_txtBlock3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get albums data from Picasa server - null returned!.
        /// </summary>
        public static string p2_AlbumList_NullReturned {
            get {
                return ResourceManager.GetString("p2_AlbumList_NullReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Album.
        /// </summary>
        public static string p2_CreateNewAlbumMenu {
            get {
                return ResourceManager.GetString("p2_CreateNewAlbumMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Albums Found or Cannot load images from Picasa Server.
        /// </summary>
        public static string p2_KeyNotFoundError {
            get {
                return ResourceManager.GetString("p2_KeyNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get albums data from Picasa server - web exception occured!.
        /// </summary>
        public static string p2_webException {
            get {
                return ResourceManager.GetString("p2_webException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Uploaded Successfully!.
        /// </summary>
        public static string p3_imageUploadedSuccess {
            get {
                return ResourceManager.GetString("p3_imageUploadedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No images in the Album.
        /// </summary>
        public static string p3_KeyNotFoundException {
            get {
                return ResourceManager.GetString("p3_KeyNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load images from Picasa server!.
        /// </summary>
        public static string p3_webexception {
            get {
                return ResourceManager.GetString("p3_webexception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE PIC : Are you sure?.
        /// </summary>
        public static string p4_deletePic {
            get {
                return ResourceManager.GetString("p4_deletePic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image DELETED successfully.
        /// </summary>
        public static string p4_imgDeletedSuccess {
            get {
                return ResourceManager.GetString("p4_imgDeletedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an album from previous page.
        /// </summary>
        public static string p4_selectAlbumagain {
            get {
                return ResourceManager.GetString("p4_selectAlbumagain", resourceCulture);
            }
        }
    }
}
